
<?php if ($this->canShow()): ?>
	<?php if ($this->includeTax() && $this->getTotalExclTax() >= 0): ?>
		<tr>
			<td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
				<strong><?php echo $this->helper('tax')->__('Basket Total Excl. Tax') ?></strong>
			</td>
			<td style="<?php echo $this->getStyle() ?>" class="a-right">
				<strong><?php echo $this->helper('checkout')->formatPrice($this->getTotalExclTax()) ?></strong>
			</td>
		</tr>
		<?php echo $this->renderTotals('taxes', $this->getColspan()); ?>
		<tr>
			<td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
				<strong><?php echo $this->helper('tax')->__('Basket Total Incl. Tax') ?></strong>
			</td>
			<td style="<?php echo $this->getStyle() ?>" class="a-right">
				<strong><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
			</td>
		</tr>
		<?php echo $this->getPayLaterOfferBlock()->toHtml() ?>
	<?php else: ?>
		<tr>
			<td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
				<?php echo $this->getTitle() ?>
			</td>
			<td style="<?php echo $this->getStyle() ?>" class="a-right">
				<?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
			</td>
		</tr>
		<?php echo $this->getPayLaterOfferBlock()->toHtml() ?>
	<?php endif; ?>
<?php else: ?>
	<?php if ($this->includeTax() && $this->getTotalExclTax() >= 0): ?>
		<tr>
		    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
		        <strong><?php echo $this->helper('tax')->__('Grand Total Excl. Tax') ?></strong>
		    </td>
		    <td style="<?php echo $this->getStyle() ?>" class="a-right">
		        <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotalExclTax()) ?></strong>
		    </td>
		</tr>
		<?php echo $this->renderTotals('taxes', $this->getColspan()); ?>
		<tr>
		    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
		        <strong><?php echo $this->helper('tax')->__('Grand Total Incl. Tax') ?></strong>
		    </td>
		    <td style="<?php echo $this->getStyle() ?>" class="a-right">
		        <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
		    </td>
		</tr>
	<?php else: ?>
		<tr>
		    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
		        <strong><?php echo $this->getTotal()->getTitle() ?></strong>
		    </td>
		    <td style="<?php echo $this->getStyle() ?>" class="a-right">
		        <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
		    </td>
		</tr>
	<?php endif; ?>	
<?php endif; ?>
