<?php if($this->canShow()): ?>
<script type="text/javascript">
	PayLater.GetStyles();
	var representative = PayLater.GetPaymentsWidget(<?php echo $this->getGrandTotal() ?>, '<?php echo $this->getPayLaterType() ?>');
	if ($('representative-wrap')) {
		$('representative-wrap').update(representative);
	}
</script>
<div style="position:relative">
	<div id="representative-wrap" style="position:absolute;left:20px;top:-30px;">

	</div>
</div>
<?php endif; ?>