<?php if($this->canShow()): ?>
<script type="text/javascript">
	var payLaterButton = PayLater.GetPaymentButton(<?php echo $this->getQuoteGrandTotal() ?>);
	$('paylater-button').update(payLaterButton);
</script>
<div id="paylater-button">
	
</div>
<div id="paylater-customer-note">
	<?php echo $this->getCustomerNote() ?>
</div>
<?php else: ?>
<button type="submit" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout" onclick="review.save();"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
<?php endif; ?>