<tr class="paylater-review-row">
	<td style="<?php echo $this->getParentBlock()->getStyle() ?>" class="a-right" colspan="<?php echo $this->getParentBlock()->getColspan(); ?>">

		<script type="text/javascript">
			var offer = PayLater.getOffer(<?php echo $this->getParentBlock()->getTotal()->getValue() ?>);
			if (PayLater.IsAmountSuitable(<?php echo $this->getParentBlock()->getTotal()->getValue() ?>)) {
				textInfoTitle = "<span class='break'>Pay just <span class='relevant amount'>&pound;" + offer.transactionFeePrice + "</span> today and </span><span class='break'>3 monthly payments of just <span class='relevant amount'>&pound;" + offer.paymentInstallmentAmount + "</span></span>";
				$('paylater-text-info').update(textInfoTitle);
				$('paylater-amount').update('&pound;' + offer.transactionFeePrice + '');
				var totalToBePaid = parseFloat(<?php echo $this->getParentBlock()->getTotal()->getValue() ?>) + parseFloat(offer.transactionFeePrice);
				$('paylater-total-payable').update('&pound;' + totalToBePaid + '');
			}
		</script>
		<?php echo $this->__('What you pay today') ?>
	</td>
	<td style="<?php echo $this->getParentBlock()->getStyle() ?>" class="a-right">
		<div id="paylater-amount"></div>
	</td>
</tr>

<tr class="paylater-review-row">
	<td style="<?php echo $this->getParentBlock()->getStyle() ?>" class="a-right" colspan="<?php echo $this->getParentBlock()->getColspan(); ?>">
		<?php echo $this->__('What you will pay in total') ?>
	</td>
	<td style="<?php echo $this->getParentBlock()->getStyle() ?>" class="a-right">
		<div id="paylater-total-payable"></div>
	</td>
</tr>
