<form action="<?php echo $this->getActionUrl() ?>" method="post" name="PayLaterForm" id="paylater-form">
	<?php $payLater = $this->collectPayLaterData(); ?>
	<?php foreach ($payLater as $key => $value): ?>
		<?php if (!is_array($value)): ?>
			<input type="hidden" name="<?php echo $key ?>" value="<?php echo $value ?>" />
		<?php else: ?>
			<?php foreach ($value as $index => $item): ?>
				<?php foreach ($item as $itemKey => $itemValue): ?>
					<input type="hidden" name="<?php echo $key ?>[<?php echo $index ?>].<?php echo $itemKey ?>" value="<?php echo $itemValue ?>" />
				<?php endforeach; ?>
			<?php endforeach; ?>
		<?php endif; ?>
	<?php endforeach; ?>
</form>
<script language="JavaScript" type="text/javascript">
	var paymentform = document.getElementById('paylater-form');
    window.onload = paymentform.submit();
</script>